// Browser port of the exact V10.7 source logic.


const RASI_EN=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const RASI_TA=['மேஷம்','ரிஷபம்','மிதுனம்','கடகம்','சிம்மம்','கன்னி','துலாம்','விருச்சிகம்','தனுசு','மகரம்','கும்பம்','மீனம்'];
const PLANET_EN=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu'];
const PLANET_TA=['சூரியன்','சந்திரன்','செவ்வாய்','புதன்','குரு','சுக்கிரன்','சனி','ராகு','கேது'];
const OWN={Sun:[4],Moon:[3],Mars:[0,7],Mercury:[2,5],Jupiter:[8,11],Venus:[1,6],Saturn:[9,10]};
const EXALT={Sun:0,Moon:1,Mars:9,Mercury:5,Jupiter:3,Venus:11,Saturn:6};
const DEBIL={Sun:6,Moon:7,Mars:3,Mercury:11,Jupiter:9,Venus:5,Saturn:0};
const NAR_TABLE=[
 [['Ar','Ta','Ge','Cn','Le','Vi','Li','Sc','Sg','Cp','Aq','Pi'],['Ar','Ta','Ge','Cn','Le','Vi','Li','Sc','Sg','Cp','Aq','Pi'],['Ar','Pi','Aq','Cp','Sg','Sc','Li','Vi','Le','Cn','Ge','Ta']],
 [['Ta','Sg','Cn','Aq','Vi','Ar','Sc','Ge','Cp','Le','Pi','Li'],['Ta','Ge','Cn','Le','Vi','Li','Sc','Sg','Cp','Aq','Pi','Ar'],['Ta','Li','Pi','Le','Cp','Ge','Sc','Ar','Vi','Aq','Cn','Sg']],
 [['Ge','Aq','Li','Vi','Ta','Cp','Sg','Le','Ar','Pi','Sc','Cn'],['Ge','Cn','Le','Vi','Li','Sc','Sg','Cp','Aq','Pi','Ar','Ta'],['Ge','Li','Aq','Pi','Cn','Sc','Sg','Ar','Le','Vi','Cp','Ta']],
 [['Cn','Ge','Ta','Ar','Pi','Aq','Cp','Sg','Sc','Li','Vi','Le'],['Cn','Le','Vi','Li','Sc','Sg','Cp','Aq','Pi','Ar','Ta','Ge'],['Cn','Le','Vi','Li','Sc','Sg','Cp','Aq','Pi','Ar','Ta','Ge']],
 [['Le','Cp','Ge','Sc','Ar','Vi','Aq','Cn','Sg','Ta','Li','Pi'],['Le','Vi','Li','Sc','Sg','Cp','Aq','Pi','Ar','Ta','Ge','Cn'],['Le','Pi','Li','Ta','Sg','Cn','Aq','Vi','Ar','Sc','Ge','Cp']],
 [['Vi','Cp','Ta','Ge','Li','Aq','Pi','Cn','Sc','Sg','Ar','Le'],['Vi','Li','Sc','Sg','Cp','Aq','Pi','Ar','Ta','Ge','Cn','Le'],['Vi','Ta','Cp','Sg','Le','Ar','Pi','Sc','Cn','Ge','Aq','Li']],
 [['Li','Sc','Sg','Cp','Aq','Pi','Ar','Ta','Ge','Cn','Le','Vi'],['Li','Sc','Sg','Cp','Aq','Pi','Ar','Ta','Ge','Cn','Le','Vi'],['Li','Vi','Le','Cn','Ge','Ta','Ar','Pi','Aq','Cp','Sg','Sc']],
 [['Sc','Ge','Cp','Le','Pi','Li','Ta','Sg','Cn','Aq','Vi','Ar'],['Sc','Sg','Cp','Aq','Pi','Ar','Ta','Ge','Cn','Le','Vi','Li'],['Sc','Ar','Vi','Aq','Cn','Sg','Ta','Li','Pi','Le','Cp','Ge']],
 [['Sg','Le','Ar','Pi','Sc','Cn','Ge','Aq','Li','Vi','Ta','Cp'],['Sg','Cp','Aq','Pi','Ar','Ta','Ge','Cn','Le','Vi','Li','Sc'],['Sg','Ar','Le','Vi','Cp','Ta','Ge','Li','Aq','Pi','Cn','Sc']],
 [['Cp','Sg','Sc','Li','Vi','Le','Cn','Ge','Ta','Ar','Pi','Aq'],['Cp','Aq','Pi','Ar','Ta','Ge','Cn','Le','Vi','Li','Sc','Sg'],['Cp','Aq','Pi','Ar','Ta','Ge','Cn','Le','Vi','Li','Sc','Sg']],
 [['Aq','Cn','Sg','Ta','Li','Pi','Le','Cp','Ge','Sc','Ar','Vi'],['Aq','Pi','Ar','Ta','Ge','Cn','Le','Vi','Li','Sc','Sg','Cp'],['Aq','Vi','Ar','Sc','Ge','Cp','Le','Pi','Li','Ta','Sg','Cn']],
 [['Pi','Cn','Sc','Sg','Ar','Le','Vi','Cp','Ta','Ge','Li','Aq'],['Pi','Ar','Ta','Ge','Cn','Le','Vi','Li','Sc','Sg','Cp','Aq'],['Pi','Sc','Cn','Ge','Aq','Li','Vi','Ta','Cp','Sg','Le','Ar']]
];
const SHORT={Ar:0,Ta:1,Ge:2,Cn:3,Le:4,Vi:5,Li:6,Sc:7,Sg:8,Cp:9,Aq:10,Pi:11};
const SHORT_BY_INDEX=['Ar','Ta','Ge','Cn','Le','Vi','Li','Sc','Sg','Cp','Aq','Pi'];
const KENDRA=[0,3,6,9],PANAPHARA=[1,4,7,10],APOKLIMA=[2,5,8,11];
const KC_GROUPS={
 savya1:[['Ar','Ta','Ge','Cn','Le','Vi','Li','Sc','Sg'],['Cp','Aq','Pi','Sc','Li','Vi','Cn','Le','Ge'],['Ta','Ar','Pi','Aq','Cp','Sg','Ar','Ta','Ge'],['Cn','Le','Vi','Li','Sc','Sg','Cp','Aq','Pi']],
 savya2:[['Sc','Li','Vi','Cn','Le','Ge','Ta','Ar','Pi'],['Aq','Cp','Sg','Ar','Ta','Ge','Cn','Le','Vi'],['Li','Sc','Sg','Cp','Aq','Pi','Sc','Li','Vi'],['Cn','Le','Ge','Ta','Ar','Pi','Aq','Cp','Sg']],
 apasavya1:[['Sg','Cp','Aq','Pi','Ar','Ta','Ge','Le','Cn'],['Vi','Li','Sc','Pi','Aq','Cp','Sg','Sc','Li'],['Vi','Le','Cn','Ge','Ta','Ar','Sg','Cp','Aq'],['Pi','Ar','Ta','Ge','Le','Cn','Vi','Li','Sc']],
 apasavya2:[['Pi','Aq','Cp','Sg','Sc','Li','Vi','Le','Cn'],['Ge','Ta','Ar','Sg','Cp','Aq','Pi','Ar','Ta'],['Ge','Le','Cn','Vi','Li','Sc','Pi','Aq','Cp'],['Sg','Sc','Li','Vi','Le','Cn','Ge','Ta','Ar']]
};
const KC_META={savya1:[100,85,83,86],savya2:[100,85,83,86],apasavya1:[86,83,85,100],apasavya2:[86,83,85,100]};
const KC_OWNER_YEARS={Ar:7,Sc:7,Ta:16,Li:16,Ge:9,Vi:9,Sg:10,Pi:10,Le:5,Cn:21,Cp:4,Aq:4};
const ASHT_ARCS=[{start:66+40/60,end:120,planet:'Sun',years:6},{start:120,end:160,planet:'Moon',years:15},{start:160,end:213+20/60,planet:'Mars',years:8},{start:213+20/60,end:253+20/60,planet:'Mercury',years:17},{start:253+20/60,end:293+20/60,planet:'Saturn',years:10},{start:293+20/60,end:333+20/60,planet:'Jupiter',years:19},{start:333+20/60,end:386+40/60,planet:'Rahu',years:12},{start:26+40/60,end:66+40/60,planet:'Venus',years:21}];
const ASHT_ORDER=['Sun','Moon','Mars','Mercury','Saturn','Jupiter','Rahu','Venus'];

function mod12(n){return ((n%12)+12)%12;}
function rasiIndex(lon){return mod12(Math.floor(((Number(lon)||0)%360+360)%360/30));}
function degInSign(lon){const x=((Number(lon)||0)%30+30)%30;return x;}
function oddSign(i){return [0,2,4,6,8,10].includes(i);}
function signCode(i){return SHORT_BY_INDEX[mod12(i)];}
function parseSign(v){if(typeof v==='number'&&v>=0&&v<12)return v;const s=String(v||'').trim().toLowerCase();const m={ar:0,aries:0,மேஷம்:0,ta:1,taurus:1,ரிஷபம்:1,ge:2,gemini:2,மிதுனம்:2,cn:3,cancer:3,கடகம்:3,le:4,leo:4,சிம்மம்:4,vi:5,virgo:5,கன்னி:5,li:6,libra:6,துலாம்:6,sc:7,scorpio:7,விருச்சிகம்:7,sg:8,sagittarius:8,தனுசு:8,cp:9,capricorn:9,மகரம்:9,aq:10,aquarius:10,கும்பம்:10,pi:11,pisces:11,மீனம்:11};return m[s]??-1;}
function planetKey(v){const s=String(v||'').trim();const m={'சூரியன்':'Sun','சந்திரன்':'Moon','செவ்வாய்':'Mars','புதன்':'Mercury','குரு':'Jupiter','சுக்கிரன்':'Venus','சனி':'Saturn','ராகு':'Rahu','கேது':'Ketu'};return m[s]||s;}
function getPlanets(chart){const out={};for(const p of (chart?.planets||[])){const k=planetKey(p.name);out[k]={...p,sign:rasiIndex(p.longitude),degree:degInSign(p.longitude)};}return out;}
function ownLord(sign, planets){const owners=sign===0?['Sun']:sign===1?['Venus']:sign===2?['Mercury']:sign===3?['Moon']:sign===4?['Sun']:sign===5?['Mercury']:sign===6?['Venus']:sign===7?['Mars','Ketu']:sign===8?['Jupiter']:sign===9?['Saturn']:sign===10?['Saturn','Rahu']:['Jupiter'];
 if(owners.length===1)return owners[0];
 const scores=owners.map(pl=>{const p=planets[pl];let s=p?1:0;if(p&&EXALT[pl]===p.sign)s+=3;if(p&&DEBIL[pl]===p.sign)s-=2;if(p&&[0,2,4,6,8,10].includes(p.sign))s+=0.25;return {pl,s};}).sort((a,b)=>b.s-a.s);return scores[0]?.pl||owners[0];}
function occupiedCount(sign,planets){return Object.values(planets).filter(p=>p.sign===sign).length;}
function signStrength(sign,planets){let s=occupiedCount(sign,planets)*10;const l=ownLord(sign,planets),p=planets[l];if(p){s+=5;if(EXALT[l]===p.sign)s+=20;if(DEBIL[l]===p.sign)s-=10;s+=Math.max(0,15-p.degree)/15;}return s+(sign===4?1:0);}
function strongerSign(a,b,planets){if(a<0)return b;if(b<0)return a;const sa=signStrength(a,planets),sb=signStrength(b,planets);if(Math.abs(sa-sb)>1e-9)return sa>sb?a:b;return occupiedCount(a,planets)>=occupiedCount(b,planets)?a:b;}
function rasiAspects(sign){if([0,3,6,9].includes(sign))return [1,4,7,10].filter(x=>x!==sign);if([1,4,7,10].includes(sign))return [0,3,6,9].filter(x=>x!==sign);return [2,5,8,11].filter(x=>x!==sign);}
function narayanaLength(sign,planets){const lord=ownLord(sign,planets),p=planets[lord];if(!p)return 1;let count;if(oddSign(sign))count=mod12(p.sign-sign)+1;else count=mod12(sign-p.sign)+1;let y=count-1;if(count===1)y=12;if(EXALT[lord]===p.sign)y+=1;if(DEBIL[lord]===p.sign)y-=1;return Math.max(0,y);}
function progressionByTable(seed,planets){const s=signCode(seed);let mode=0;if(planets.Saturn?.sign===seed)mode=1;else if(planets.Ketu?.sign===seed)mode=2;const row=NAR_TABLE[seed][mode];return row.map(x=>SHORT[x]);}
function addYears(date,years){return new Date(date.getTime()+Number(years||0)*365.2425*86400000);}
function fmt(d){return isNaN(d?.getTime?.())?'—':d.toISOString().slice(0,10);}
function periodRows(order,lengthFn,startDate,firstFraction=1,cycles=1){let cur=new Date(startDate),rows=[];for(let c=0;c<cycles;c++){for(let i=0;i<order.length;i++){const sign=order[i],full=Number(lengthFn(sign,i,c)||0),years=(c===0&&i===0)?full*firstFraction:full;const st=new Date(cur),en=addYears(st,years);rows.push({rasi:sign,years,start:fmt(st),end:fmt(en),fullYears:full,cycle:c+1});cur=en;}}return rows;}
function equalRasiSubs(md,order,lengthFn){const each=md.years/12;let cur=new Date(md.start+'T00:00:00Z');return order.map(r=>{const st=new Date(cur),en=addYears(st,each);cur=en;return {rasi:r,years:each,start:fmt(st),end:fmt(en)};});}
function narayanaSubOrder(dasaRasi,planets){const seed=strongerSign(dasaRasi,mod12(dasaRasi+6),planets);const lord=ownLord(seed,planets),p=planets[lord];let start=p?.sign??seed;let dir=oddSign(start)?1:-1;if(planets.Saturn?.sign===seed)dir=1;if(planets.Ketu?.sign===seed)dir*=-1;return Array.from({length:12},(_,i)=>mod12(start+i*dir));}
function addSubperiods(rows,orderFn,count){return rows.map(md=>{const order=orderFn(md.rasi).slice(0,count);let cur=new Date(md.start+'T00:00:00Z');const each=md.years/count;const subs=order.map(r=>{const st=new Date(cur),en=addYears(st,each);cur=en;return {rasi:r,years:each,start:fmt(st),end:fmt(en)};});return {...md,antardasas:subs};});}
function ashtottari(chart,startDate){const p=getPlanets(chart),moon=p.Moon?.longitude; if(!Number.isFinite(moon))return {available:false,reason:'Moon longitude unavailable'};let L=((moon%360)+360)%360,z=L<26+40/60?L+360:L;let arc=ASHT_ARCS.find(a=>z>=a.start&&z<a.end)||ASHT_ARCS[0];const frac=(arc.end-z)/(arc.end-arc.start);const idx=ASHT_ORDER.indexOf(arc.planet);const seq=Array.from({length:8},(_,i)=>ASHT_ORDER[(idx+i)%8]);let cur=new Date(startDate),rows=[];seq.forEach((pl,i)=>{const years=ASHT_ARCS.find(a=>a.planet===pl).years*(i===0?frac:1),st=new Date(cur),en=addYears(st,years);rows.push({lord:pl,years,start:fmt(st),end:fmt(en)});cur=en;});const subs=rows.map(md=>{const stIdx=seq.indexOf(md.lord),ords=Array.from({length:8},(_,i)=>seq[(stIdx+1+i)%8]);let c=new Date(md.start+'T00:00:00Z');return {...md,antardasas:ords.map(pl=>{const y=md.years*(ASHT_ARCS.find(a=>a.planet===pl).years/108),s=new Date(c),e=addYears(s,y);c=e;return {lord:pl,years:y,start:fmt(s),end:fmt(e)};})};});return {available:true,title:'Ashtottari Dasa',cycleYears:108,firstLord:arc.planet,birthBalanceFraction:frac,sequence:subs,applicability:'Conditional in the supplied reference; applicability is debated.'};}
function narayana(chart,startDate){const p=getPlanets(chart),lagna=Number.isFinite(chart?.lagna?.longitude)?rasiIndex(chart.lagna.longitude):-1;if(lagna<0)return {available:false,reason:'Lagna unavailable'};const seed=strongerSign(lagna,mod12(lagna+6),p);const order=progressionByTable(seed,p);let rows=periodRows(order,s=>narayanaLength(s,p),startDate,1,2);rows=addSubperiods(rows,r=>narayanaSubOrder(r,p),12);return {available:true,title:'Narayana Dasa',seed,sequence:rows,method:'PDF Table 40 progression and Narayana rasi-length rules; second-cycle lengths are not expanded beyond the first 24 periods.'};}
function kendradi(chart,startDate,seedOverride,sree=false){const p=getPlanets(chart),lagna=rasiIndex(chart.lagna?.longitude);const seed=seedOverride>=0?seedOverride:strongerSign(lagna,mod12(lagna+6),p);let dir=oddSign(sree?seed:lagna)?1:-1;if(p.Saturn?.sign===seed)dir=1;if(p.Ketu?.sign===seed)dir*=-1;const offs=[0,3,6,9,1,4,7,10,2,5,8,11];const order=offs.map(o=>mod12(seed+o*dir));const slDeg=degInSign(chart.__sreeLagnaLongitude||0);const frac=sree?Math.max(0,(30-slDeg)/30):1;const rows=periodRows(order,s=>narayanaLength(s,p),startDate,frac,2);return {available:true,title:sree?'Sudasa':'Lagna Kendradi Rasi Dasa',seed,sequence:rows,firstFraction:frac};}
function drigdasa(chart,startDate){const p=getPlanets(chart),lagna=rasiIndex(chart.lagna?.longitude);const groups=[mod12(lagna+8),mod12(lagna+9),mod12(lagna+10)],order=[];for(const g of groups){const dir=oddSign(g)?1:-1;const candidates=[g,...rasiAspects(g)];const seen=[];for(let step=0;step<12&&seen.length<4;step++){const x=mod12(g+step*dir);if(candidates.includes(x)&&!seen.includes(x))seen.push(x);}for(const x of seen)if(!order.includes(x))order.push(x);}for(let x=0;order.length<12&&x<12;x++)if(!order.includes(x))order.push(x);return {available:true,title:'Drigdasa',seed:groups[0],sequence:periodRows(order,s=>narayanaLength(s,p),startDate,1,2),groups};}
function niryaanaShoola(chart,startDate){const p=getPlanets(chart),lagna=rasiIndex(chart.lagna?.longitude),a=mod12(lagna+1),b=mod12(lagna+7),seed=strongerSign(a,b,p),dir=oddSign(seed)?1:-1,order=Array.from({length:12},(_,i)=>mod12(seed+i*dir));return {available:true,title:'Niryaana Shoola Dasa',seed,sequence:addSubperiods(periodRows(order,s=>[0,3,6,9].includes(s)?7:[1,4,7,10].includes(s)?8:9,startDate),r=>narayanaSubOrder(r,p),12),note:'The supplied reference notes that antardasa rules are not explicit and recommends Narayana-style rules.'};}
function shoola(chart,startDate){const p=getPlanets(chart),lagna=rasiIndex(chart.lagna?.longitude),seed=strongerSign(lagna,mod12(lagna+6),p),order=Array.from({length:12},(_,i)=>mod12(seed+i));return {available:true,title:'Shoola Dasa',seed,sequence:addSubperiods(periodRows(order,()=>9,startDate),r=>narayanaSubOrder(r,p),12)};}
function sreeLagnaLongitude(chart){const moon=Number(chart.planets?.find(x=>planetKey(x.name)==='Moon')?.longitude),lagna=Number(chart.lagna?.longitude);if(!Number.isFinite(moon)||!Number.isFinite(lagna))return NaN;const nak=13+1/3,adv=((moon%nak)+nak)%nak;return ((lagna+(adv/nak)*360)%360+360)%360;}
function kalachakra(chart,startDate){const moon=Number(chart.planets?.find(x=>planetKey(x.name)==='Moon')?.longitude);if(!Number.isFinite(moon))return {available:false,reason:'Moon longitude unavailable'};const nak=Math.floor(((moon%360)+360)%360/(13+1/3)),pada=Math.floor(((((moon%360)+360)%360)%(13+1/3))/(3+1/3));const savya=[0,1,2,6,7,8,12,13,14,18,19,20,24,25,26].includes(nak);const savya1=[0,2,6,8,12,14,18,20,24,26].includes(nak);const group=savya?(savya1?'savya1':'savya2'):([3,9,15,21].includes(nak)?'apasavya1':'apasavya2');const seq9=KC_GROUPS[group][pada];const param=KC_META[group][pada];const posInPada=((((moon%360)+360)%360)%(13+1/3))%(3+1/3);const elapsed=(posInPada/(3+1/3))*param;let cum=0,startIndex=0,remaining=0;for(let i=0;i<seq9.length;i++){const y=KC_OWNER_YEARS[seq9[i]];if(elapsed>=cum+y)cum+=y;else{startIndex=i;remaining=y-(elapsed-cum);break;}}const order=[];let currentGroup=group,currentPada=pada;let localSeq=seq9.slice(startIndex);while(order.length<12){for(const r of localSeq)if(order.length<12)order.push(r);let nextPada=(currentPada+1)%4;if(nextPada===0){currentGroup=currentGroup==='savya1'?'savya2':currentGroup==='savya2'?'savya1':currentGroup==='apasavya1'?'apasavya2':'apasavya1';}localSeq=KC_GROUPS[currentGroup][nextPada];currentPada=nextPada;}let cur=new Date(startDate),rows=[];order.forEach((r,i)=>{const full=KC_OWNER_YEARS[r],years=i===0?remaining:full,st=new Date(cur),en=addYears(st,years);rows.push({rasi:SHORT[r],years,start:fmt(st),end:fmt(en)});cur=en;});const withSubs=rows.map(md=>{const ord=[];for(let i=0;i<9;i++){let idx=order.indexOf(SHORT[parseSign(md.rasi)]);if(idx<0)idx=0;ord.push(order[(idx+i)%order.length]);}let c=new Date(md.start+'T00:00:00Z');return {...md,antardasas:ord.map(r=>{const y=md.years*(KC_OWNER_YEARS[r]/seq9.reduce((a,x)=>a+KC_OWNER_YEARS[x],0)),s=new Date(c),e=addYears(s,y);c=e;return {rasi:r,years:y,start:fmt(s),end:fmt(e)};})};});return {available:true,title:'Kalachakra Dasa',nakshatraIndex:nak+1,pada:pada+1,group,sequence:withSubs,dehaRasi:seq9[0],jeevaRasi:seq9[8],paramayush:param};}
function phase4Dasa(chart){const start=new Date(`${chart.birthDate||chart.date||'2000-01-01'}T00:00:00Z`);const sl=sreeLagnaLongitude(chart);const c=JSON.parse(JSON.stringify(chart));c.__sreeLagnaLongitude=sl;return {ashtottari:ashtottari(chart,start),narayana:narayana(chart,start),lagnaKendradi:kendradi(chart,start,-1,false),sudasa:kendradi(c,start,rasiIndex(sl),true),drigdasa:drigdasa(chart,start),niryaanaShoola:niryaanaShoola(chart,start),shoola:shoola(chart,start),kalachakra:kalachakra(chart,start),sreeLagnaLongitude:sl};}
export {phase4Dasa};
